# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3a7cb5644c10c164cde443840f5fa8af"
name = "avenrun-bundles-3"
application_url = "https://avenrun-bundles-3.onrender.com"
embedded = true

[access_scopes]
scopes = "write_products,write_metaobjects,write_metaobject_definitions,write_discounts,read_discounts"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [
  "https://avenrun-bundles-3.onrender.com/auth/callback",
  "https://avenrun-bundles-3.onrender.com/auth/shopify/callback",
  "https://avenrun-bundles-3.onrender.com/api/auth/callback"
]

[build]
automatically_update_urls_on_dev = true

